"""Song class field name updated

Revision ID: 628e9385e5a7
Revises: d2e78b71477c
Create Date: 2023-12-26 15:31:19.939780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628e9385e5a7'
down_revision = 'd2e78b71477c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_song_author_author', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_song_author_id_author'), 'author', ['author_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_song_author_id_author'), type_='foreignkey')
        batch_op.create_foreign_key('fk_song_author_author', 'author', ['author'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
