"""empty message

Revision ID: 9c094a68d2df
Revises: 0160681f5ec9
Create Date: 2023-12-15 15:38:47.817220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c094a68d2df'
down_revision = '0160681f5ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('author', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_name'), ['name'], unique=False)

    op.create_table('songs_to_learn',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs_to_learn')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_name'))
        batch_op.drop_index(batch_op.f('ix_song_author'))

    op.drop_table('song')
    # ### end Alembic commands ###
