"""Author model added

Revision ID: d2e78b71477c
Revises: 3104827963aa
Create Date: 2023-12-26 14:16:12.447803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e78b71477c'
down_revision = '3104827963aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('ix_song_author')
        batch_op.create_foreign_key(batch_op.f('fk_song_author_author'), 'author', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_song_author_author'), type_='foreignkey')
        batch_op.create_index('ix_song_author', ['author'], unique=False)
        batch_op.alter_column('author',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
